"""
citation_utils.py — Citation Generator & Paper Export Utilities
================================================================
Generates citations in APA, IEEE, and MLA formats from arXiv paper metadata.
Also provides journal recommendation logic and Zotero-compatible BibTeX export.

All free — no external APIs needed.
"""

from datetime import datetime
import re


def clean_title_for_bibtex(title: str) -> str:
    """Clean title for use in BibTeX keys and entries."""
    return re.sub(r'[^a-zA-Z0-9\s]', '', title).strip()


def generate_bibtex_key(paper: dict) -> str:
    """Generate a unique BibTeX key: FirstAuthorYear_FirstTitleWord"""
    author_part = "unknown"
    if paper.get("authors"):
        first_author = paper["authors"].split(",")[0].strip().split()[-1]  # Last name
        author_part  = re.sub(r'[^a-zA-Z]', '', first_author)

    year = paper.get("year", "0000")

    title_words = clean_title_for_bibtex(paper.get("title", "")).split()
    title_part = title_words[0] if title_words else "paper"

    return f"{author_part}{year}_{title_part}".lower()


def format_apa(paper: dict) -> str:
    """
    APA 7th Edition format:
    Author, A. A., & Author, B. B. (Year). Title of article. Journal Name.
    https://doi.org/xxxxx
    """
    authors = paper.get("authors", "Unknown Author")
    # Convert "FirstName LastName, ..." to "LastName, F.," format (simplified)
    author_parts = []
    for a in authors.split(",")[:3]:
        a = a.strip()
        if not a:
            continue
        parts = a.split()
        if len(parts) >= 2:
            last = parts[-1]
            initials = ". ".join(p[0].upper() for p in parts[:-1]) + "."
            author_parts.append(f"{last}, {initials}")
        else:
            author_parts.append(a)

    if len(authors.split(",")) > 3:
        author_str = ", ".join(author_parts) + ", et al."
    else:
        author_str = ", & ".join(author_parts) if len(author_parts) > 1 else (author_parts[0] if author_parts else "Unknown")

    year  = paper.get("year", "n.d.")
    title = paper.get("title", "Untitled")
    link  = paper.get("link", "")

    return f"{author_str} ({year}). {title}. *arXiv preprint*. {link}"


def format_ieee(paper: dict, ref_num: int = 1) -> str:
    """
    IEEE format:
    [1] A. Author, B. Author, "Title," in Proc. Conference, Year, pp. xx-xx.
    """
    authors = paper.get("authors", "Unknown")
    # Convert to "A. LastName" format (simplified)
    author_parts = []
    for a in authors.split(",")[:3]:
        a = a.strip()
        if not a:
            continue
        parts = a.split()
        if len(parts) >= 2:
            initials = ". ".join(p[0].upper() for p in parts[:-1])
            author_parts.append(f"{initials}. {parts[-1]}")
        else:
            author_parts.append(a)

    if len(authors.split(",")) > 3:
        author_str = ", ".join(author_parts) + " et al."
    else:
        author_str = " and ".join(author_parts) if author_parts else "Unknown"

    year  = paper.get("year", "n.d.")
    title = paper.get("title", "Untitled")
    link  = paper.get("link", "")

    return f'[{ref_num}] {author_str}, "{title}," *arXiv preprint*, {year}. [Online]. Available: {link}'


def format_mla(paper: dict) -> str:
    """
    MLA 9th Edition format:
    LastName, FirstName. "Title." Journal, Year.
    """
    authors = paper.get("authors", "Unknown Author")
    first_author = authors.split(",")[0].strip()
    parts = first_author.split()
    if len(parts) >= 2:
        formatted = f"{parts[-1]}, {' '.join(parts[:-1])}"
    else:
        formatted = first_author

    year  = paper.get("year", "n.d.")
    title = paper.get("title", "Untitled")
    link  = paper.get("link", "")

    return f'{formatted}. "{title}." *arXiv preprint*, {year}, {link}.'


def generate_bibtex(paper: dict) -> str:
    """Generate BibTeX entry for Zotero/Mendeley/LaTeX."""
    key     = generate_bibtex_key(paper)
    title   = paper.get("title", "Untitled")
    authors = paper.get("authors", "Unknown").replace(", ", " and ")
    year    = paper.get("year", "2024")
    link    = paper.get("link", "")
    # Extract arXiv ID from URL
    arxiv_id = link.split("/abs/")[-1] if "/abs/" in link else link

    return f"""@article{{{key},
  title   = {{{title}}},
  author  = {{{authors}}},
  year    = {{{year}}},
  journal = {{arXiv preprint}},
  url     = {{{link}}},
  eprint  = {{{arxiv_id}}},
  archivePrefix = {{arXiv}},
}}"""


def generate_all_bibtex(papers: list) -> str:
    """Generate BibTeX file for all papers."""
    entries = [generate_bibtex(p) for p in papers]
    header = f"% BibTeX bibliography generated by AI Research Assistant\n% Date: {datetime.now().strftime('%Y-%m-%d')}\n% Papers: {len(papers)}\n\n"
    return header + "\n\n".join(entries)


# ── Journal/Conference Recommendation Engine ──────────────────────────────────

PUBLICATION_VENUES = [
    # Free to publish + widely accepted
    {
        "name": "arXiv Preprint Server",
        "type": "Preprint",
        "cost": "Free",
        "deadline": "Rolling",
        "impact": "High visibility, instant publication",
        "url": "https://arxiv.org",
        "categories": ["all"],
        "tip": "Publish here first to establish priority. Then submit to a journal.",
        "suitability": "all"
    },
    {
        "name": "IRJET (International Research Journal of Engineering & Technology)",
        "type": "Journal",
        "cost": "Free / Low cost",
        "deadline": "Monthly",
        "impact": "Accepted by most Indian universities for BE projects",
        "url": "https://www.irjet.net",
        "categories": ["engineering", "cs", "data science"],
        "tip": "Very beginner-friendly. Good for first-time authors.",
        "suitability": "student"
    },
    {
        "name": "IJERT (International Journal of Engineering Research & Technology)",
        "type": "Journal",
        "cost": "Free",
        "deadline": "Monthly",
        "impact": "UGC-CARE listed, accepted by VTU and similar universities",
        "url": "https://www.ijert.org",
        "categories": ["engineering", "cs"],
        "tip": "Check if your university recognizes it. Most VTU-affiliated colleges do.",
        "suitability": "student"
    },
    {
        "name": "IEEE Access",
        "type": "Journal",
        "cost": "APC required for OA (dept can fund)",
        "deadline": "Rolling",
        "impact": "High — indexed in Scopus, Web of Science. IF: 3.9",
        "url": "https://ieeeaccess.ieee.org",
        "categories": ["engineering", "cs", "ai"],
        "tip": "If your guide is a co-author, apply for IEEE waiver. Strong industry recognition.",
        "suitability": "advanced"
    },
    {
        "name": "PLOS ONE",
        "type": "Journal",
        "cost": "APC but has fee waivers",
        "deadline": "Rolling",
        "impact": "High — multidisciplinary, IF: 3.7, fully open access",
        "url": "https://journals.plos.org/plosone",
        "categories": ["all"],
        "tip": "Apply for APC waiver if from a low-income country. Strong global reach.",
        "suitability": "advanced"
    },
    {
        "name": "Springer LNCS Conferences",
        "type": "Conference",
        "cost": "Registration fee (often covered by dept)",
        "deadline": "Varies by conference",
        "impact": "Good — Scopus indexed, proceedings published",
        "url": "https://link.springer.com/bookseries/558",
        "categories": ["cs", "ai", "ml"],
        "tip": "Look for ICACDS, ICCIDS, ICTIS — common venues for Indian student papers.",
        "suitability": "intermediate"
    },
    {
        "name": "JAIR (Journal of AI Research)",
        "type": "Journal",
        "cost": "Completely Free",
        "deadline": "Rolling",
        "impact": "High — free to publish AND read. IF: 4.9",
        "url": "https://www.jair.org",
        "categories": ["ai", "ml"],
        "tip": "Best free journal for pure AI/ML work. Requires strong experimental rigor.",
        "suitability": "advanced"
    },
    {
        "name": "ACM Student Research Competition",
        "type": "Conference",
        "cost": "Free for students",
        "deadline": "Varies",
        "impact": "Prestigious — ACM branded, great for resume",
        "url": "https://src.acm.org",
        "categories": ["cs", "hci", "ai"],
        "tip": "Shorter paper format (4 pages). Perfect for a focused BE project.",
        "suitability": "student"
    },
    {
        "name": "ResearchGate / Academia.edu",
        "type": "Repository",
        "cost": "Free",
        "deadline": "Anytime",
        "impact": "Medium — good for visibility and citation tracking",
        "url": "https://www.researchgate.net",
        "categories": ["all"],
        "tip": "Not peer-reviewed, but useful for sharing and getting early feedback.",
        "suitability": "all"
    },
]


def recommend_venues(topic: str = "", experience_level: str = "student") -> list:
    """Return venue recommendations filtered by experience level."""
    level_filter = {
        "First paper (student)": ["student", "all"],
        "Intermediate": ["student", "intermediate", "all"],
        "Advanced / with guide": ["student", "intermediate", "advanced", "all"],
    }
    allowed = level_filter.get(experience_level, ["student", "all"])
    return [v for v in PUBLICATION_VENUES if v["suitability"] in allowed]


def render_citation_panel(papers: list):
    """
    Streamlit UI component for citation generation.
    Called from within another page (e.g., draft generator).
    """
    import streamlit as st

    if not papers:
        st.info("No papers selected. Select papers in Paper Finder first.")
        return

    st.markdown('<div class="section-header">📚 Citation Generator</div>', unsafe_allow_html=True)

    col1, col2 = st.columns([2, 1])
    with col1:
        fmt = st.selectbox("Citation Format", ["APA 7th", "IEEE", "MLA 9th", "BibTeX (LaTeX/Zotero)"])
    with col2:
        st.markdown("<br>", unsafe_allow_html=True)
        export_all = st.button("📋 Copy All", use_container_width=True)

    citations = []
    for i, p in enumerate(papers):
        if fmt == "APA 7th":
            citations.append(format_apa(p))
        elif fmt == "IEEE":
            citations.append(format_ieee(p, i + 1))
        elif fmt == "MLA 9th":
            citations.append(format_mla(p))
        elif fmt == "BibTeX (LaTeX/Zotero)":
            citations.append(generate_bibtex(p))

    if fmt == "BibTeX (LaTeX/Zotero)":
        bibtex_all = generate_all_bibtex(papers)
        st.code(bibtex_all[:3000] + ("…" if len(bibtex_all) > 3000 else ""), language="bibtex")
        st.download_button("⬇️ Download .bib file", data=bibtex_all,
                          file_name="references.bib", mime="text/plain")
    else:
        citation_text = "\n\n".join(citations)
        st.text_area("Generated Citations (copy-paste into your paper)", citation_text, height=250)
        st.download_button(
            f"⬇️ Download as .txt",
            data=citation_text,
            file_name=f"citations_{fmt.split()[0].lower()}.txt",
            mime="text/plain"
        )